title : Wendal随笔
tagline: Ruhoh
author :
  name : wendal chen
  email : wendal1985@gmail.com
  github : wendal
  twitter : wendal_x
  feedburner : wendal

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
